### ISSUE TITLE
Kontorsøk: Flytte adressesøk fra tpsws til PDL

### ISSUE THREAD

**Issue by ojnybo** [navikt/nav-office-search-api#6]
![image](https://user-images.githubusercontent.com/47320658/153615264-f01bf0fb-3dff-47db-b6d0-ace1879791a2.png)

Undersøk om PDL har en tjeneste for adressesøk vi kan erstatte tpsws-aura med.
Når vi ikke lenger konsumerer den gamle tjenesten, gi beskjed til @ThomasKasene

**Comment by ojnybo** [comment]
PDL har ikke dataene vi er avhengige av, og kommer neppe til å få det heller.

**Comment by ThomasKasene** [comment]
Synes kanskje ikke det blir riktig å lukke issuet; `tpsws-aura` _kommer til_ å dø, og før den tid må dere ha funnet noe annet 😃
Jeg er immidlertid enig i at tittelen på dette issuet ikke blir dekkende for den fremtidige løsningen (siden PDL ikke har opplysningene). Lager du et nytt issue på det noe sted? For saken er ikke ute av verden, men den bør kanskje løftes høyere.
